image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

build:
  stage: build
  script:
    - cp config.live.js config.js 
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  image: python:3.11
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws --version
    - aws s3 sync dist/ s3://$S3_BUCKET_NAME/ --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

  only:
    - main